version: '3.8'

services:
    we-fappy:
        build:
            context: .
            dockerfile: Dockerfile.we-flappy
        restart: always
        container_name: we-fappy
        ports:
            - 127.0.0.1:92:8000
        networks:
            - caddy
        labels:
            caddy: marica-adam.domafoldi.hu
            caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
